# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170112_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='obstables',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='structure_challenges',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='themes',
            field=models.TextField(blank=True),
        ),
    ]
