# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 15:04
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20170112_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'D\xe9partement'},
        ),
        migrations.AlterModelOptions(
            name='intervention',
            options={'verbose_name': 'Intervention'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'Pilote'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Projet'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'R\xe9gion'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Calendrier'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Comp\xe9tence'},
        ),
        migrations.AlterModelOptions(
            name='stakeholder',
            options={'verbose_name': 'Acteur'},
        ),
        migrations.AlterModelOptions(
            name='structureposition',
            options={'verbose_name': 'Positionnement'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='ddt_reference_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ddt_reference_service',
        ),
        migrations.AlterField(
            model_name='interventiontype',
            name='intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Intervention', verbose_name='Intervention'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_firstname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Pr\xe9nom'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_function',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_lastname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_mail',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='T\xe9l\xe9phone'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_service',
            field=models.CharField(blank=True, max_length=255, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Department', verbose_name='D\xe9partement'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description du projet en 5 lignes max.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='epci_name',
            field=models.CharField(blank=True, max_length=255, verbose_name="Nom de l'EPCI"),
        ),
        migrations.AlterField(
            model_name='project',
            name='epci_siren',
            field=models.CharField(blank=True, max_length=255, verbose_name="N\xb0 SIREN de l'EPCI"),
        ),
        migrations.AlterField(
            model_name='project',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='P\xe9rim\xe8tre SIG'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Manager', verbose_name='Pilote'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager_detail',
            field=models.TextField(blank=True, verbose_name='Pr\xe9cision sur le pilotage'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager_other',
            field=models.CharField(blank=True, max_length=255, verbose_name='Autre pilote, pr\xe9ciser'),
        ),
        migrations.AlterField(
            model_name='project',
            name='missing_skills',
            field=models.ManyToManyField(related_name='missing_skill', to='projects.Skill', verbose_name='Comp\xe9tences manquantes'),
        ),
        migrations.AlterField(
            model_name='project',
            name='mobilized_skills',
            field=models.ManyToManyField(related_name='mobilized_skill', to='projects.Skill', verbose_name='Comp\xe9tences mobilis\xe9es'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='project',
            name='obstables',
            field=models.TextField(blank=True, verbose_name='Blocages rencontr\xe9s, comment ont \xe9t\xe9 lev\xe9s les blocages (10 lignes max.)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='other_perimeter',
            field=models.CharField(blank=True, max_length=255, verbose_name='Autre p\xe9rim\xe8tre (\xe0 pr\xe9ciser)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Region', verbose_name='R\xe9gion'),
        ),
        migrations.AlterField(
            model_name='project',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Schedule', verbose_name="Calendrier d'accompagnement"),
        ),
        migrations.AlterField(
            model_name='project',
            name='structure_challenges',
            field=models.TextField(blank=True, verbose_name='Missions / enjeux pour votre structure (5 lignes max.)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='themes',
            field=models.TextField(blank=True, verbose_name="Th\xe9matiques / portes d'entr\xe9e dominantes (production de logement, transition \xe9nerg\xe9tique, accessibilit\xe9, revitalisation de centre-bourg, etc.)"),
        ),
        migrations.AlterField(
            model_name='project',
            name='town_insee',
            field=models.CharField(blank=True, max_length=255, verbose_name='Code INSEE de la commune'),
        ),
        migrations.AlterField(
            model_name='project',
            name='town_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Non de la commune'),
        ),
        migrations.AlterField(
            model_name='stakeholdertype',
            name='stakeholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.StakeHolder', verbose_name='Acteur'),
        ),
        migrations.AlterField(
            model_name='structurepositiontype',
            name='structure_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.StructurePosition', verbose_name='Positionnement'),
        ),
    ]
