# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20170127_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contact_firstname',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contact_function',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contact_lastname',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contact_mail',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contact_service',
        ),
    ]
