# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20170127_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=255, verbose_name='Pr\xe9nom')),
                ('lastname', models.CharField(max_length=255, verbose_name='Nom')),
                ('function', models.CharField(blank=True, max_length=255, verbose_name='Fonction')),
                ('service', models.CharField(blank=True, max_length=255, verbose_name='Service')),
                ('mail', models.CharField(max_length=255, verbose_name='Mail')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='T\xe9l\xe9phone')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Structure')),
            ],
        ),
        migrations.AddField(
            model_name='referent',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Structure', verbose_name='Structure'),
        ),
        migrations.AddField(
            model_name='project',
            name='referents',
            field=models.ManyToManyField(to='projects.Referent'),
        ),
    ]
