# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20170127_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structurepositiontype',
            name='project',
        ),
        migrations.RemoveField(
            model_name='structurepositiontype',
            name='structure_position',
        ),
        migrations.RemoveField(
            model_name='project',
            name='structure_positions',
        ),
        migrations.DeleteModel(
            name='StructurePosition',
        ),
        migrations.DeleteModel(
            name='StructurePositionType',
        ),
    ]
