# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_project_manager_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interventiontype',
            name='intervention',
        ),
        migrations.RemoveField(
            model_name='interventiontype',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='interventions',
        ),
        migrations.DeleteModel(
            name='InterventionType',
        ),
    ]
