# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20170127_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='interventions',
            field=models.ManyToManyField(to='projects.Intervention'),
        ),
    ]
