# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_interventions'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='missing_skills_others',
            field=models.CharField(blank=True, max_length=255, verbose_name='Autres comp\xe9tences manquantes'),
        ),
        migrations.AddField(
            model_name='project',
            name='mobilized_skills_others',
            field=models.CharField(blank=True, max_length=255, verbose_name='Autres comp\xe9tences mobilis\xe9es'),
        ),
    ]
