# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20170127_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'El\xe9ment d\xe9clencheur',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='triggers_others',
            field=models.CharField(blank=True, max_length=255, verbose_name='Autres \xe9l\xe9ments d\xe9clencheurs'),
        ),
        migrations.AddField(
            model_name='project',
            name='triggers',
            field=models.ManyToManyField(to='projects.Trigger', verbose_name='El\xe9ments d\xe9clencheur'),
        ),
    ]
