# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_remove_project_themes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Th\xe9matique',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='themes_others',
            field=models.CharField(blank=True, max_length=255, verbose_name='Autres th\xe9matiques'),
        ),
        migrations.AddField(
            model_name='project',
            name='themes',
            field=models.ManyToManyField(to='projects.Theme', verbose_name="Th\xe9matiques / portes d'entr\xe9e dominantes (production de logement, transition \xe9nerg\xe9tique, accessibilit\xe9, revitalisation de centre-bourg, etc.)"),
        ),
    ]
