# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20170127_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='themes',
            field=models.ManyToManyField(to='projects.Theme', verbose_name='Th\xe9matiques'),
        ),
    ]
