# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-28 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20170127_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='5 lignes maximum', verbose_name='Description du projet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom du projet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_leader_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Priv\xe9')], max_length=255, verbose_name='Type de porteur de projet'),
        ),
    ]
