# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-30 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20170128_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('public', 'Public'), ('private', 'Priv\xe9')], max_length=255, verbose_name='Type de porteur de projet')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nom du porteur de projet')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_leader_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_leader_type',
        ),
        migrations.AddField(
            model_name='leader',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
