# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-30 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20170130_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Champ libre'),
        ),
        migrations.AlterField(
            model_name='project',
            name='interventions_others',
            field=models.CharField(blank=True, max_length=255, verbose_name='Autres interventions'),
        ),
        migrations.AlterField(
            model_name='project',
            name='obstables',
            field=models.TextField(blank=True, help_text='10 lignes max.', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='referent',
            name='service',
            field=models.CharField(blank=True, max_length=255, verbose_name='Service (\xe9viter les sigles)'),
        ),
    ]
