# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20170227_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='project',
            name='manager_other',
        ),
    ]
