# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_stakeholdertype_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='missing_skills',
        ),
        migrations.RemoveField(
            model_name='project',
            name='missing_skills_others',
        ),
        migrations.RemoveField(
            model_name='project',
            name='mobilized_skills',
        ),
        migrations.RemoveField(
            model_name='project',
            name='mobilized_skills_others',
        ),
        migrations.AlterField(
            model_name='stakeholdertype',
            name='manager',
            field=models.BooleanField(default=None, verbose_name='Pilote'),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
