# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20170227_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='begin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de d\xe9but de projet'),
        ),
        migrations.AddField(
            model_name='project',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='Date pr\xe9visionnelle de fin de projet'),
        ),
    ]
