# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_project_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachment/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('in_progress', 'en cours'), ('completed', 'achev\xe9')], default='in_progress', max_length=12, verbose_name='Etat du projet'),
        ),
    ]
