# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachment/', verbose_name='Pi\xe8ce jointe'),
        ),
        migrations.AlterField(
            model_name='project',
            name='interventions',
            field=models.ManyToManyField(blank=True, to='projects.Intervention'),
        ),
        migrations.AlterField(
            model_name='project',
            name='referents',
            field=models.ManyToManyField(blank=True, to='projects.Referent'),
        ),
        migrations.AlterField(
            model_name='project',
            name='themes',
            field=models.ManyToManyField(blank=True, to='projects.Theme', verbose_name='Th\xe9matiques'),
        ),
        migrations.AlterField(
            model_name='project',
            name='triggers',
            field=models.ManyToManyField(blank=True, to='projects.Trigger', verbose_name='El\xe9ments d\xe9clencheur'),
        ),
    ]
