# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_auto_20170227_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='stakeholders',
            field=models.ManyToManyField(blank=True, through='projects.StakeHolderType', to='projects.StakeHolder'),
        ),
    ]
