# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_auto_20170227_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='referents',
        ),
    ]
