# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_remove_project_referents'),
    ]

    operations = [
        migrations.AddField(
            model_name='referent',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
