# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-24 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_auto_20170420_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trigger',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_departmental',
            field=models.CharField(blank=True, help_text="Pr\xe9ciser le type de financement d\xe9partemental s'il y a lieu", max_length=255, verbose_name='Financement d\xe9partemental'),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_european',
            field=models.CharField(blank=True, help_text="Pr\xe9ciser le type de financement europ\xe9en s'il y a lieu", max_length=255, verbose_name='Financement europ\xe9en'),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_national',
            field=models.CharField(blank=True, help_text="Pr\xe9ciser le type de financement national s'il y a lieu", max_length=255, verbose_name='Financement national'),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_other',
            field=models.CharField(blank=True, help_text='Pr\xe9ciser de quel autre type de financement le projet a b\xe9n\xe9ficier', max_length=255, verbose_name='Autre financement'),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_regional',
            field=models.CharField(blank=True, help_text="Pr\xe9ciser le type de financement r\xe9gional s'il y a lieu", max_length=255, verbose_name='Financement r\xe9gional'),
        ),
        migrations.AlterField(
            model_name='project',
            name='stakeholders',
            field=models.ManyToManyField(blank=True, through='projects.StakeHolderType', to='projects.StakeHolder', verbose_name="Acteurs de l'ing\xe9nierie mobilis\xe9s"),
        ),
        migrations.AlterField(
            model_name='project',
            name='structure_challenges',
            field=models.TextField(blank=True, help_text='5 lignes maximum', verbose_name='Missions / enjeux pour votre structure'),
        ),
    ]
