# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-24 20:31
from __future__ import unicode_literals
import os
import json

from django.db import migrations
from django.contrib.gis.geos import GEOSGeometry, GeometryCollection

dir_path = os.path.dirname(os.path.realpath(__file__))

def import_data(apps, schema_editor):
    Department = apps.get_model("projects", "Department")
    Region = apps.get_model("projects", "Region")
    path_dep = os.path.join(dir_path, 'data', 'departements.geojson')
    path_reg = os.path.join(dir_path, 'data', 'regions.geojson')
    with open(path_dep) as f:
        data = json.load(f)
        for feature in data['features']:
            geo = feature['geometry']
            code = feature['properties']['code']
            name = feature['properties']['nom']
            geom = GeometryCollection(GEOSGeometry(json.dumps(geo)))
            departement, created = Department.objects.get_or_create(insee=code, defaults={'name':name, 'geom':geom})

    with open(path_reg) as f:
        data = json.load(f)
        for feature in data['features']:
            geo = feature['geometry']
            code = feature['properties']['code']
            name = feature['properties']['nom']
            geom = GeometryCollection(GEOSGeometry(json.dumps(geo)))
            region, created = Region.objects.get_or_create(insee=code, defaults={'name':name, 'geom':geom})


def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_auto_20170424_2030'),
    ]

    operations = [
        migrations.RunPython(import_data, reverse_func),
    ]
